### ISSUE TITLE
"e" is too high in the cutout stickers

### ISSUE THREAD

**Issue by kytrinyx** [exercism/marketing#1]
I had a few stickers made, with the diameter of the black circle at 2 inches, which covers the apple on the laptop exactly:

![img_6433](https://cloud.githubusercontent.com/assets/276834/21968001/2e8b3078-db4d-11e6-8e28-1b7e0be49ca2.JPG)

The horns on the "e" get cut off about a millimeter. I can't apply the sticker lower down so that the horns don't get cut off, because then the leaf of the apple isn't covered.

@troubalex What would you suggest here? I can think of two solutions, either move the e further down (so it is not centered vertically), or make the e smaller. Or perhaps make the e smaller and order stickers that are larger than 2 inches in diameter.

**Comment by troubalex** [comment]
Given that it already ticks you off that the horns are cut off by about a millimeter, I don't think moving the e down and setting it off center is a good idea. 😉  

If you're happy with the sticker size, I think we should simply make the e smaller. Won't be much if it's really just a millimeter. Is it the top of the horns that gets cut or the side?

**Comment by kytrinyx** [comment]
> Given that it already ticks you off that the horns are cut off by about a millimeter, I don't think moving the e down and setting it off center is a good idea. 

LOL. You are absolutely right.

It's the top tips of the horns that get cut off, and just barely.

**Comment by troubalex** [comment]
I'll try to get it done tomorrow. Should be a quick fix.
